import MainNav from '@/components/main-nav'
import '../globals.css'
import type { Metadata } from 'next'
import { Questrial } from 'next/font/google'
import Footer from '@/components/footer'

const font = Questrial({ weight: ["400"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Real state',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <MainNav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
